### PR TITLE
Migrate to Groovy and fix availability value.

### LINKED ISSUE #271: Availability dropdown is empty when creating template
When you create a template, if you expand the experimental options before saving, the Availability dropdown has no options. Appears to populate after saving and returning to the template.

### PR DESCRIPTION
**Pull request by KostyaSha**
Closes #271

### CODE REVIEW

File: docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/utils/Functions.java [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+import java.util.ArrayList;
+import java.util.List;
+
+/**
+ * UI helper class.
+ *
+ * @author Kanstantsin Shautsou
+ */
+public class Functions {
+    public Functions() {
```
Comment (lanwen) [inline docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/utils/Functions.java]: no need to write default empty public constructor

File: docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/utils/Functions.java [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+    }
+
+    public static Class getDockerTemplateBase() {
```
Comment (lanwen) [inline docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/utils/Functions.java]: why without generic?

File: docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/utils/Functions.java (hunk 1 above)
Comment (KostyaSha) [inline docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/utils/Functions.java]: copy from hudson.. i had idea do page binding but then skipped...

File: docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/utils/Functions.java [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+
+import java.util.ArrayList;
+import java.util.List;
+
+/**
+ * UI helper class.
+ *
+ * @author Kanstantsin Shautsou
+ */
+public class Functions {
```
Comment (lanwen) [inline docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/utils/Functions.java]: maybe name it as UIFunctions or UIHelpers?

Comment (KostyaSha) [inline docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/utils/Functions.java]: Named like` hudson.Functions `

File: docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/utils/Functions.java (hunk 2 above)
Comment (KostyaSha) [inline docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/utils/Functions.java]: more interesting where it was required, because it definitely was required somewhere :(

Comment (KostyaSha) [inline docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/utils/Functions.java]: reverted back where it was. Will keep for now. Will clean on next releases.

File: docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/utils/Functions.java (hunk 1 above)
Comment (KostyaSha) [inline docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/utils/Functions.java]: just removed

File: docker-plugin/src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplate/config.groovy [hunk 4]
```diff
@@ -0,0 +1,80 @@
...
+            if (sd != null) {
+                def prefix = sd.displayName.equals("Docker Once Retention Strategy") ? "" : "Experimental: "
+
+                f.dropdownListBlock(value: sd.clazz.name, name: sd.displayName,
+                        selected: instance.retentionStrategy != null ?
+                                instance.retentionStrategy.descriptor.equals(sd) : false,
+                        title: prefix + sd.displayName) {
+                    descriptor = sd
+                    f.invisibleEntry() {
+                        input(type: "hidden", name: "stapler-class", value: sd.clazz.name)
```
Comment (lanwen) [inline docker-plugin/src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplate/config.groovy]: `stapler-class` is deprecated

File: docker-plugin/src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplate/config.groovy [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+
+    f.entry(title: _("# of executors"), field: "numExecutors") {
+        f.number(default: "1")
+    }
+}
+
+f.dropdownList(name: "launcher", title: _("Launch method"),
+        help: descriptor.getHelpFile('launcher')) {
+    Functions.dockerComputerLauncherDescriptors.each { ld ->
+        if (ld != null) {
```
Comment (lanwen) [inline docker-plugin/src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplate/config.groovy]: so many logic in view! :|

File: docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/utils/Functions.java (hunk 3 above)
Comment (lanwen) [inline docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/utils/Functions.java]: So if u wanna use `hudson.Functions`, you can't use import - you should write full class name

File: docker-plugin/src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplate/config.groovy (hunk 5 above)
Comment (KostyaSha) [inline docker-plugin/src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplate/config.groovy]: I just converted crazy jelly, hope something can be simplified in future, now i don't want break something.

File: docker-plugin/src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplate/config.groovy (hunk 4 above)
Comment (KostyaSha) [inline docker-plugin/src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplate/config.groovy]: i just copied that is used! When somebody describe all this magic, then i will be glad to do modern way :P

File: docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/utils/Functions.java (hunk 3 above)
Comment (KostyaSha) [inline docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/utils/Functions.java]: DockerFunctions! bingo

**Comment by lanwen** [comment]
:+1:
