### PR TITLE
Fix show persisted launchers.

### LINKED ISSUE #285: Incorrect containers' credentials being displayed on the config page after an upgrade to 0.10.1
I have upgraded Docker Plugin 0.10.0 to 0.10.1 and now when I navigate to the config page I can see that the containers' credentials settings are being displayed incorrectly.

It seems that they are set correctly in the config file but for some reason they're set incorrectly on the config page.

If I hit save then the incorrect settings are being saved to the config file.

I've attached a screenshot of the container section of the config page before and after an upgrade.

Docker Plugin 0.10.0:

screen shot 2015-07-22 at 11 33 39

Docker Plugin 0.10.1:

screen shot 2015-07-22 at 11 25 06

### PR DESCRIPTION
**Pull request by KostyaSha**
Fix #285.

### CODE REVIEW

File: docker-plugin/src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplate/config.groovy [hunk 1]
```diff
@@ -36,10 +36,13 @@ f.advanced(title: _("Experimental Options"), align: "left") {
                 def prefix = sd.displayName.equals("Docker Once Retention Strategy") ? "" : "Experimental: "
 
                 f.dropdownListBlock(value: sd.clazz.name, name: sd.displayName,
-                        selected: instance.retentionStrategy != null ?
-                                instance.retentionStrategy.descriptor.equals(sd) : false,
+                        selected: instance.retentionStrategy == null ?
+                                false : instance.retentionStrategy.descriptor.equals(sd),
```
Comment (KostyaSha) [inline docker-plugin/src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplate/config.groovy]: just did constant with second dropdownListBlock

File: docker-plugin/src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplate/config.groovy [hunk 2]
```diff
@@ -36,10 +36,13 @@ f.advanced(title: _("Experimental Options"), align: "left") {
...
                         title: prefix + sd.displayName) {
                     descriptor = sd
+                    if (instance.retentionStrategy != null && instance.retentionStrategy.descriptor.equals(sd)) {
+                        instance = instance.retentionStrategy
```
Comment (KostyaSha) [inline docker-plugin/src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplate/config.groovy]: in my manual tests it doesn't influence

File: docker-plugin/src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplate/config.groovy [hunk 3]
```diff
@@ -62,6 +65,9 @@ f.dropdownList(name: "launcher", title: _("Launch method"),
                     selected: instance.launcher == null ? false : instance.launcher.descriptor.equals(ld),
                     title: ld.displayName) {
                 descriptor = ld
+                if (instance.launcher != null && instance.launcher.descriptor.equals(ld)) {
```
Comment (KostyaSha) [inline docker-plugin/src/main/resources/com/nirima/jenkins/plugins/docker/DockerTemplate/config.groovy]: but this block fixes showing selected with right data

**Comment by KostyaSha** [comment]
Verified by requester.
