### PR TITLE
#712 Infer registry URL from Template image name

### LINKED ISSUE #712: Unable to specify private docker registry in Configure Jenkins -> Cloud
- [1.1.5 ] docker-plugin version you use

 - [2.138 ] jenkins version you use

 - [ ] docker engine version you use
Version = 1.12.6, API Version = 1.24

 - [ ] stack trace / logs / any technical details that could help diagnose this issue

We host a private docker registry from which i want to pull images. Unfortunately providing the Docker Image as <registry>/imagename:latest and have also provided the credentials id to <registry>. However I get the below error when the plugin tries to pull down the image. I can also see that the registry URL seems to be null in the 

`Error in provisioning; template='DockerTemplate{configVersion=2, labelString='docker-iib-build', connector=io.jenkins.docker.connector.DockerComputerSSHConnector@1596d10b, remoteFs='/home/jenkins', instanceCap=2147483647, mode=EXCLUSIVE, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@62fe5c4, dockerTemplateBase=DockerTemplateBase{image='**registry.xxxxxxx/integration_automation/int-docker-jenkins-slave-iib-build**', pullCredentialsId='xxxxxxx', registry=### **DockerRegistryEndpoint[null;credentialsId=xxxxxxx]**, dockerCommand='', hostname='', dnsHosts=[], network='', volumes=[/home/cloud-user/jenkins:/home/jenkins], volumesFrom2=[], environment=[], bindPorts='', bindAllPorts=true, memoryLimit=null, memorySwap=null, cpuShares=null, shmSize=null, privileged=false, tty=false, macAddress='null', extraHosts=[]}, removeVolumes=false, pullStrategy=PULL_LATEST, nodeProperties=[], disabled=BySystem,0 ms,9.9 sec,Template provisioning failed.}' for cloud='docker-iib-build'
com.github.dockerjava.api.exception.NotFoundException: {"message":"No such image: registry.gitlab.mycompany.com/gitlab_group/int-docker-jenkins-slave-iib-build:latest"}

	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:103)
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
Caused: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: registry.gitlab.mycompany.com/gitlab_group/int-docker-jenkins-slave-iib-build:latest
	at com.nirima.jenkins.plugins.docker.DockerTemplate.pullImage(DockerTemplate.java:511)
	at com.nirima.jenkins.plugins.docker.DockerTemplate.provisionNode(DockerTemplate.java:519)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.run(DockerCloud.java:365)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Jan 03, 2019 9:58:20 PM WARNING hudson.slaves.NodeProvisioner$2 run
Unexpected exception encountered while provisioning agent Image of registry.gitlab.mycompany.com/gitlab_group/int-docker-jenkins-slave-iib-build
com.github.dockerjava.api.exception.NotFoundException: {"message":"No such image: registry.gitlab.mycompany.com/gitlab_group/int-docker-jenkins-slave-iib-build:latest"}

	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:103)
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
Caused: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: registry.gitlab.mycompany.com/gitlab_group/int-docker-jenkins-slave-iib-build:latest
	at com.nirima.jenkins.plugins.docker.DockerTemplate.pullImage(DockerTemplate.java:511)
	at com.nirima.jenkins.plugins.docker.DockerTemplate.provisionNode(DockerTemplate.java:519)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.run(DockerCloud.java:365)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

### PR DESCRIPTION
**Pull request by Dohbedoh**
Addresses https://github.com/jenkinsci/docker-plugin/issues/712. Infer the registry URL from image name using the [org.jenkinsci.plugins.docker.commons.credentials.DockerRegistryEndpoint#fromImageName](https://javadoc.jenkins.io/plugin/docker-commons/index.html?org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpoint.html)

Fixes #712

### CODE REVIEW

**Comment by Dohbedoh** [comment]
A fix might be needed upstream as the `org.jenkinsci.plugins.docker.commons.credentials.DockerRegistryEndpoint#fromImageName` does not accept the syntax `hostname:port`.

File: src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplateBase.java [hunk 1]
```diff
@@ -567,7 +567,13 @@ public void setExtraDockerLabelsString(String extraDockerLabelsString) {
 
     public DockerRegistryEndpoint getRegistry() {
         if (registry == null) {
-            registry = new DockerRegistryEndpoint(null, pullCredentialsId);
+            /* TODO: Use DockerRegistryEndpoint#fromImageName when JENKINS-63243 is fixed */
+            String hostname = NameParser.resolveRepositoryName(
+                NameParser.parseRepositoryTag(getImage()).repos).hostname;
+            if(!hostname.startsWith("https://")) {
+                hostname = "https://" + hostname;
```
Comment (pjdarton) [inline src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplateBase.java:574]: Are you 100% sure that `https://` is the correct default here?
I know that docker registries _can_ use https, and if one is authenticating then it's best to use an encrypted means of communicating, but it looks like the code here would prevent someone from using `"http://hostname.domain"` as this would be turned into `"https://http://hostname.domain"` which is unlikely to work at all.

I _suspect_ that it'd be better to only prefix with `https://` if there was no protocol specified at all ... but I'm not entirely sure of that here (I'm not in a position to experiment/evaluate right now either - current work pressures are such that my time for this is limited to "review, ask questions, push merge button and hope").

File: src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplateBase.java [hunk 2]
```diff
@@ -567,7 +567,13 @@ public void setExtraDockerLabelsString(String extraDockerLabelsString) {
 
     public DockerRegistryEndpoint getRegistry() {
         if (registry == null) {
-            registry = new DockerRegistryEndpoint(null, pullCredentialsId);
+            /* TODO: Use DockerRegistryEndpoint#fromImageName when JENKINS-63243 is fixed */
```
Comment (pjdarton) [inline src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplateBase.java:570]: Is there a PR for this issue yet?

Comment (Dohbedoh) [reply src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplateBase.java:570]: https://github.com/jenkinsci/docker-commons-plugin/pull/88

File: src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplateBase.java (hunk 1 above)
Comment (Dohbedoh) [reply src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplateBase.java:574]: > I suspect that it'd be better to only prefix with https:// if there was no protocol specified at all ...

[NameParser#resolveRepositoryName](https://github.com/docker-java/docker-java/blob/3.1.5/src/main/java/com/github/dockerjava/core/NameParser.java#L103) actually throw an exception if you provide the scheme in the image name. That is to say that `http://hostname.domain/repo/name:tag` is not a valid image name. So you cannot specify `http://`.
However [NameParser#resolveRepositoryName](https://github.com/docker-java/docker-java/blob/3.1.5/src/main/java/com/github/dockerjava/core/NameParser.java#L109) use `https://index.docker.io/v1/` if there no registry specify, hence the condition.
I agree that we could just do this if there is no protocol at all.

> Are you 100% sure that https:// is the correct default here?

[DockerRegistryEndpoint](https://github.com/jenkinsci/docker-commons-plugin/blob/docker-commons-1.17/src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpoint.java#L128) is also setting `https://` for the scheme. The help says `The url is built from registry:port into https://registry:port, the same way docker push does.`.

File: src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplateBase.java (hunk 2 above)
Comment (pjdarton) [reply src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplateBase.java:646]: That PR had to wait a long time, but it looks like that PR was merged in on 24 Aug, and went into docker-commons 1.20 onwards.

Could you update this PR to use the new code (i.e. resolve the TODO comment)?
